Repository AdguardTeam/AdGuardHome, pull requests merged in 2022-08, with the labels that each got.

#4557 Update list of projects in README.md
  README.md
Labels: documentation

#4849 Added some domains to service filters
  internal/filtering/blocked.go
Labels: enhancement, P3: Medium

#4860 Color scheme based logo
  README.md
  doc/adguard_home_darkmode.svg
  doc/adguard_home_lightmode.svg
Labels: enhancement, documentation

#4877 Update Cloudflare Service
  internal/filtering/blocked.go
Labels: enhancement, P3: Medium
